name: Cycling UK application
type: module
description: Provides Cycling UK applications based on Webform with a Dynamics integration.
package: Cycling UK
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - drupal:webform
  - cycling_uk_application:cycling_uk_application_type
  - cycling_uk_application:cycling_uk_application_process
  - cycling_uk_application:cycling_uk_dynamics
