entity.cycling_uk_application_process.settings:
  path: 'admin/structure/cycling-uk-application-process'
  defaults:
    _form: '\Drupal\cycling_uk_application_process\Form\CyclingUkApplicationProcessSettingsForm'
    _title: 'Cycling uk application process'
  requirements:
    _permission: 'administer cycling uk application process'

entity.cycling_uk_application_process.collection:
  path: '/admin/applications'
  defaults:
    _entity_list: 'cycling_uk_application_process'
    _title: 'Applications'
  requirements:
    _permission: 'administer users'
