entity.cycling_uk_application_process.settings:
  title: 'Settings'
  route_name: entity.cycling_uk_application_process.settings
  base_route: entity.cycling_uk_application_process.settings
entity.cycling_uk_application_process.view:
  title: 'View'
  route_name: entity.cycling_uk_application_process.canonical
  base_route: entity.cycling_uk_application_process.canonical
entity.cycling_uk_application_process.edit_form:
  title: 'Edit'
  route_name: entity.cycling_uk_application_process.edit_form
  base_route: entity.cycling_uk_application_process.canonical
entity.cycling_uk_application_process.delete_form:
  title: 'Delete'
  route_name: entity.cycling_uk_application_process.delete_form
  base_route: entity.cycling_uk_application_process.canonical
  weight: 10
entity.cycling_uk_application_process.collection:
  title: 'Applications'
  route_name: entity.cycling_uk_application_process.collection
  base_route: entity.cycling_uk_application_process.collection
  weight: 10
