<?php

/**
 * @file
 * Contains image_styles_mapping.module.
 */

declare(strict_types = 1);

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function image_styles_mapping_help(string $route_name, RouteMatchInterface $route_match): string {
  $help = '';

  switch ($route_name) {
    case 'help.page.image_styles_mapping':
      $help = '<p>' . \t('This module allows you to have a report listing the image styles per image fields and per view modes on all entities.') . '</p>';
      $help .= '<p>' . \t('The report can be accessed <a href=":url">here</a>.', [':url' => Url::fromRoute('image_styles_mapping.report')->toString()]) . '</p>';
      return $help;
  }

  return $help;
}
