_core:
  default_config_hash: qXr9jaHRTax99ozD1dMjMZieOtW8OcQOVpZzg3a_OLY
admin_css: true
fx: blur
noscript: false
one_pixel: true
placeholder: ''
unstyled_extensions: ''
responsive_image: true
blazy:
  loadInvisible: false
  offset: 100
  saveViewportOffsetDelay: 50
  validateDelay: 25
  container: ''
io:
  unblazy: false
  rootMargin: 0px
  threshold: '0'
  disconnect: false
  enabled: true
extras: {  }
decode: false
