_core:
  default_config_hash: 85ado4cZtA7lWICPWkcHny-svJygwib0dyTvibDjBsg
instance_uri: 'https://cyclinguklive.crm11.dynamics.com/'
application_id: ae6a4d62-f0bf-42c6-bf26-e7265a4678f0
endpoint: 'https://cyclinguklive.api.crm11.dynamics.com/api/data/v9.2/'
entity_whitelist:
  - cuk_actionsubscriptionupload
application_secret: X1D8Q~iSjxOQj7OA2Gi~9cagh4m36p~0CEFjrck_
