_core:
  default_config_hash: Wph0IY6FThC4QuHAGcSQDx6S8gysoclVsF2tkm4Lu8o
langcode: en
uuid: 8b285985-b9fc-4005-aeab-c6b7c4272ec7
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_only: null
eu_only_js: null
popup_position: false
fixed_top_position: false
popup_info:
  value: "<h2>Cookies</h2>\r\n\r\n<p>We use cookies to help our site work, to understand how it is used and to tailor ads that are more relevant to you and your interests. You can read our policy here:</p>\r\n"
  format: basic_html
mobile_popup_info:
  value: ''
  format: basic_html
popup_info_template: new
popup_agree_button_message: Accept
popup_more_info_button_message: 'Cookie Policy'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: 'No, thanks'
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: basic_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: 'https://www.cyclinguk.org/cookies-policy'
popup_link_new_window: true
popup_height: null
popup_width: ''
popup_delay: 1000
show_more_info: true
popup_bg_hex: ''
popup_text_hex: ''
domain: ''
domains_option: 1
domains_list: ''
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 100
use_mobile_message: false
use_bare_css: true
disagree_do_not_show_popup: false
reload_page: false
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
method: categories
disabled_javascripts: ''
automatic_cookies_removal: true
allowed_cookies: "necessary:c_uk_fn\r\nnecessary:c_uk_ln\r\nnecessary:c_uk_em\r\nnecessary:colourContrast\r\nnecessary:fontSize\r\nnecessary:Drupal.tableDrag.showWeight\r\nnecessary:DrupalModuleFilter\r\nnecessary:has_js\r\nnecessary:_hjIncludedInPageviewSample\r\nnecessary:_hjIncludedInSessionSample\r\nnecessary:_hjAbsoluteSessionInProgress\r\nnecessary:_hjid\r\nnecessary:_hjTLDTest\r\nmarketing:_ga\r\nmarketing:_gat\r\nmarketing:_gid"
consent_storage_method: do_not_store
withdraw_message:
  value: "<h2>We use cookies on this site to enhance your user experience</h2>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
  format: basic_html
withdraw_tab_button_label: 'Privacy settings'
withdraw_action_button_label: 'Withdraw consent'
withdraw_enabled: false
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: false
containing_element: body
cookie_policy_version: 1.0.0
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
close_button_action: close_banner
reject_button_label: ''
reject_button_enabled: false
close_button_enabled: false
