_core:
  default_config_hash: UYGkeE2iH3UGp9lBPsELb3VSgHz9vkMJeaGzcYwE7Uw
settings:
  library_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js'
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css'
  crop_preview_image_style: crop_thumbnail
  crop_list:
    crop_16_9: crop_16_9
    crop_21_9: crop_21_9
    crop_2_3: crop_2_3
  crop_types_required:
    crop_16_9: crop_16_9
    crop_21_9: crop_21_9
    crop_2_3: crop_2_3
  warn_multiple_usages: true
  show_default_crop: true
  show_crop_area: false
  notify_apply: true
  notify_update: true
