pca_fields:
  -
    element: address_line1
    field: Line1
    mode: 2
    enabled: true
  -
    element: address_line2
    field: Line2
    mode: 2
    enabled: true
  -
    element: postal_code
    field: PostalCode
    mode: 2
    enabled: true
  -
    element: locality
    field: City
    mode: 2
    enabled: true
  -
    element: dependent_locality
    field: ''
    mode: 0
    enabled: false
  -
    element: administrative_area
    field: ''
    mode: 0
    enabled: false
  -
    element: sorting_code
    field: ''
    mode: 0
    enabled: false
  -
    element: country_code
    field: ''
    mode: 0
    enabled: false
  -
    element: organization
    field: ''
    mode: 0
    enabled: false
_core:
  default_config_hash: oE5vdXyhTPRN6VufzFkF20mg7pN1eJjWks5MXzzToNI
