_core:
  default_config_hash: XYBhThrygaiT05udG2RDldLL_Qc0AJRmr-LbQ1indBM
media_skyfish_api_key: qUoQllIbyqwnyQF2imJRiUlEUDW7L25cTWxWCg4HdAmjvl0pOLHzjtvCx9G0PKXz
media_skyfish_api_secret: PzxTiR5uRCt6qmyyPmSR6lZPV1tBa9983YZfrjrfhkldVV3Zjwnxow4urcLG9c5z
media_skyfish_global_user: sacha.wellborn@cyclinguk.org
media_skyfish_global_password: kMvVbz83RJmI
media_skyfish_cache: '60'
