_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
smtp_on: false
smtp_host: smtp.sendgrid.net
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: apikey
smtp_password: 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
smtp_from: no-reply@cyclinguk.org
smtp_fromname: 'Cycling UK'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_reroute_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: true
