<?php

/**
 * @file
 * Provides a cycling uk application type entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function cycling_uk_application_type_theme() {
  return [
    'cycling_uk_application_type' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for cycling uk application type templates.
 *
 * Default template: cycling-uk-application-type.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the cycling uk application type information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_cycling_uk_application_type(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
