entity.cycling_uk_application_type.settings:
  path: 'admin/structure/cycling-uk-application-type'
  defaults:
    _form: '\Drupal\cycling_uk_application_type\Form\CyclingUkApplicationTypeSettingsForm'
    _title: 'Cycling UK application type'
  requirements:
    _permission: 'administer cycling uk application type'

entity.cycling_uk_application_type.collection:
  path: '/admin/applications/types'
  defaults:
    _entity_list: 'cycling_uk_application_type'
    _title: 'Roles'
  requirements:
    _permission: 'administer permissions'
